name: Shared Test Workflow

on:
  workflow_call:
    inputs:
      test-command:
        type: string
        required: false
        description: "The npm script to run for testing"
        default: 'test'
      skip-cache:
        type: boolean
        required: false
        description: 'Set to true to skip node_modules/npm caching'
        default: 'false'
      skip-draft-prs:
        type: boolean
        required: false
        description: 'Set to true to skip draft PR check'
        default: 'false'

jobs:
  integration-test:
    if: |
      !(inputs.skip-draft-prs == true && github.event.pull_request.draft == true)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
          # Only fetch the latest commit (shallow clone)
          fetch-depth: 1
          # Ensure we only fetch the branch that triggered the workflow
          persist-credentials: false

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version-file: './package.json'
        cache: ${{ inputs.skip-cache == 'true' && '' || 'npm' }}

    - name: Get Node Version from package.json
      id: node-version
      shell: bash
      run: |
        # Extract raw value from package.json
        RAW=$(node -p "require('./package.json').engines?.node || ''")
        
        if [ -z "$RAW" ]; then
          echo "::error file=package.json::Missing 'engines.node' in package.json"
          exit 1
        fi

        # Trim version: e.g., ">=20.1.0" becomes "20.1.0"
        TRIMMED=$(echo $RAW | sed 's/[^0-9.]*//g')
        
        # Set as an output for subsequent steps
        echo "version=$TRIMMED" >> $GITHUB_OUTPUT

    - name: Cache node_modules
      if: ${{ inputs.skip-cache != 'true' }}
      id: cache-nodemodules
      uses: actions/cache@v4
      with:
        path: node_modules
        # Key includes OS, Node version, and lockfile hash
        key: ${{ runner.os }}-node-${{ steps.node-version.outputs.version }}-${{ hashFiles('./package.json', './package-lock.json') }}

    - name: Install dependencies
      if: steps.cache-nodemodules.outputs.cache-hit != 'true'
      run: npm i
      shell: bash

    - name: Run tests
      run: npm run ${{ inputs.test-command }}
      shell: bash